// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX0QY5k4fX3qAryZIo_Ftl91q3OB8Z7DU',
    appId: '1:440741088386:web:59ab073dda772adf19389b',
    messagingSenderId: '440741088386',
    projectId: 'flutter-app-firebase-10825',
    authDomain: 'flutter-app-firebase-10825.firebaseapp.com',
    storageBucket: 'flutter-app-firebase-10825.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsmt6aPFv56Y5HQHNnFgW7fIi676oG6U',
    appId: '1:440741088386:android:12d9412969b7a54d19389b',
    messagingSenderId: '440741088386',
    projectId: 'flutter-app-firebase-10825',
    storageBucket: 'flutter-app-firebase-10825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCam7kLYzw0jhQzxqzUfgof8cr1pL1bNc0',
    appId: '1:440741088386:ios:3b2ec748beeb977519389b',
    messagingSenderId: '440741088386',
    projectId: 'flutter-app-firebase-10825',
    storageBucket: 'flutter-app-firebase-10825.firebasestorage.app',
    iosBundleId: 'com.example.bankingFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCam7kLYzw0jhQzxqzUfgof8cr1pL1bNc0',
    appId: '1:440741088386:ios:3b2ec748beeb977519389b',
    messagingSenderId: '440741088386',
    projectId: 'flutter-app-firebase-10825',
    storageBucket: 'flutter-app-firebase-10825.firebasestorage.app',
    iosBundleId: 'com.example.bankingFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX0QY5k4fX3qAryZIo_Ftl91q3OB8Z7DU',
    appId: '1:440741088386:web:f81acb970834898b19389b',
    messagingSenderId: '440741088386',
    projectId: 'flutter-app-firebase-10825',
    authDomain: 'flutter-app-firebase-10825.firebaseapp.com',
    storageBucket: 'flutter-app-firebase-10825.firebasestorage.app',
  );
}
